name: Central Security Scan

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ### ───── Setup Runtime Based on Language ─────
      - name: Setup Node.js
        if: inputs.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        if: inputs.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (Node)
        if: inputs.language == 'node'
        run: npm ci

      - name: Install dependencies (Python)
        if: inputs.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      ### ───── Run Semgrep ─────
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'auto'  # Use 'p/ci' or custom config if preferred
          args: --json --output=semgrep.json          
        continue-on-error: true
        
      - name: Upload Semgrep Results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json

      ### ───── Run TruffleHog ─────
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .          

      ### ───── Run Snyk Scan ─────

      - name: Run Snyk test
        uses: snyk/actions/node@master
        with:
          args: test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Merge SARIF files (optional)
        run: |
          jq -s 'reduce .[] as $item ({}; . + $item)' snyk-*.sarif > snyk-merged.sarif
      
      - name: Upload Snyk SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-merged.sarif

      - name: Snyk monitor all projects
        uses: snyk/actions/node@master
        with:
          args: monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
