name: Central Security Scan

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ### ───── Setup Runtime Based on Language ─────
      - name: Setup Node.js
        if: inputs.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        if: inputs.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (Node)
        if: inputs.language == 'node'
        run: npm ci

      - name: Install dependencies (Python)
        if: inputs.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      ### ───── Run Semgrep ─────
      - name: Run Semgrep with SARIF output
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          args: --sarif --output=semgrep.sarif
        continue-on-error: true
      
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

      ### ───── Run TruffleHog ─────
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          extra_args: --source=git file://. --fail         

      ### ───── Run Snyk Scan ─────

      - name: Snyk test
        uses: snyk/actions/node@master
        with:
          args: test --all-projects --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Snyk monitor all projects
        uses: snyk/actions/node@master
        with:
          args: monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
